

GET http://localhost:5000/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo4LCJpc3MiOiJiZWxhamFyLXJlc3QtYXBpLWdvbGFuZyIsImV4cCI6MTc2MDk5ODI2OSwiaWF0IjoxNzYwOTExODY5fQ.eGi_i6IHgqfU5tKjbQy5ZCme7vy3-71-W_55dvK6RnI
Accept: application/json

### REGISTER USER
POST http://localhost:5000/api/users/register
Accept: application/json
Content-Type: application/json

{
  "username": "",
  "email": "groudonhooh@gmail.com",
  "password": "groudon123"
}

### LOGIN USER
POST http://localhost:5000/api/users/login
Accept: application/json
Content-Type: application/json

{
  "email": "groudonhooh@gmail.com",
  "password": "groudon123"
}


### CREAT NEW POST

POST http://localhost:5000/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJpc3MiOiJiZWxhamFyLXJlc3QtYXBpLWdvbGFuZyIsImV4cCI6MTc2MjEwMDM0MSwiaWF0IjoxNzYyMDEzOTQxfQ.jF3IOTObk3uH5iA1tiRG7UyaVMbzpGQddP33I6izlfE
Content-Type: application/json

{
  "title": "LAPANGAN MENGGUNAKAN TEKNOLOGI AI3",
  "content": "PERKEMBAGAN AI SANGAT PESAT DENGAN INOVASI TERBARU YANG AKAN MENGUBAH DUNIA DI MASA DEPAN",
  "image_url": "https://cdn.grid.id/crop/0x0:0x0/700x465/photo/2024/11/15/lapangan-sepak-bolajpg-20241115074613.jpg",
  "category_ids": [2, 4]
}

### GET PRODUCT BY ID
GET http://localhost:5000/api/posts/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozLCJpc3MiOiJiZWxhamFyLXJlc3QtYXBpLWdvbGFuZyIsImV4cCI6MTc2MTI0NDQwNSwiaWF0IjoxNzYxMTU4MDA1fQ.U1bQblonjdtRAkEgjXigvpxzgAkLDo_sSNyvEED-m-8
Accept: application/json


### DELETE PRODUCT
DELETE http://localhost:5000/api/posts/17
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozLCJpc3MiOiJiZWxhamFyLXJlc3QtYXBpLWdvbGFuZyIsImV4cCI6MTc2MTI0MjY5NiwiaWF0IjoxNzYxMTU2Mjk2fQ.h_zuCwOtwoWsvy1OWTbbul-lMtWWEjbceW5YZb_A_vA
Accept: application/json

### UPDATE NEW POST
PUT http://localhost:5000/api/posts/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJpc3MiOiJiZWxhamFyLXJlc3QtYXBpLWdvbGFuZyIsImV4cCI6MTc2MjEwMDM0MSwiaWF0IjoxNzYyMDEzOTQxfQ.jF3IOTObk3uH5iA1tiRG7UyaVMbzpGQddP33I6izlfE
Content-Type: application/json

{
  "title": "",
  "content": "PERKEMBAGAN AI SANGAT PESAT DENGAN INOVASI TERBARU YANG AKAN MENGUBAH DUNIA DI MASA DEPAN",
  "image_url": "https://specials-images.forbesimg.com/imageserve/6669d56e40a694388fdc74ea/Robot-fishing-on-jetty--3d-rendering/960x0.jpg?fit=scale"
}

### CREATE COMMENT
POST http://localhost:5000/api/posts/2/comments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJpc3MiOiJiZWxhamFyLXJlc3QtYXBpLWdvbGFuZyIsImV4cCI6MTc2MjEwMDM0MSwiaWF0IjoxNzYyMDEzOTQxfQ.jF3IOTObk3uH5iA1tiRG7UyaVMbzpGQddP33I6izlfE
Content-Type: application/json

{
  "content": "APAAN SI KELIATAN BANGET HAX NYA"
}

### CREAT NEW CATEGORY
POST http://localhost:5000/api/categories
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJpc3MiOiJiZWxhamFyLXJlc3QtYXBpLWdvbGFuZyIsImV4cCI6MTc2MjEwMDM0MSwiaWF0IjoxNzYyMDEzOTQxfQ.jF3IOTObk3uH5iA1tiRG7UyaVMbzpGQddP33I6izlfE
Content-Type: application/json

{
  "name": "bisnis"
}

### GET ALL CATEGORIES
GET http://localhost:5000/api/categories
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJpc3MiOiJiZWxhamFyLXJlc3QtYXBpLWdvbGFuZyIsImV4cCI6MTc2MjEwMDM0MSwiaWF0IjoxNzYyMDEzOTQxfQ.jF3IOTObk3uH5iA1tiRG7UyaVMbzpGQddP33I6izlfE
Accept: application/json